changelog:
  exclude:
    labels:
      - skip-changelog

  categories:
    - title: General
      labels:
        - "*"
      exclude:
        labels:
          - dependencies
    - title: Dependencies
      labels:
        - dependencies
