apiVersion: v2
name: k8s-sustain
description: Kubernetes operator for sustainability use cases (right-sizing workloads).
type: application
version: 0.1.0
appVersion: "0.1.0"

dependencies:
  - name: kube-prometheus-stack
    version: "67.x.x"
    repository: https://prometheus-community.github.io/helm-charts
    condition: kube-prometheus-stack.enabled
