run:
  timeout: 5m

linters:
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused
    - gosimple
    - gocritic
    - gofmt
    - misspell
    - unconvert
    - unparam
    - errorlint
    - nilerr
    - bodyclose

linters-settings:
  govet:
    shadow: true
  errorlint:
    errorf: true
    asserts: true
    comparison: true

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck
        - unparam
    - path: zz_generated
      linters:
        - all
