version: "2"
run:
  timeout: 2m

linters:
  default: standard

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck
        - unparam
    - path: zz_generated
      linters:
        - all
