{{- if .Values.controller.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "k8s-sustain.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "k8s-sustain.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "k8s-sustain.selectorLabels" . | nindent 6 }}
  endpoints:
    - port: metrics
      interval: {{ .Values.controller.serviceMonitor.interval }}
      scrapeTimeout: {{ .Values.controller.serviceMonitor.scrapeTimeout }}
{{- end }}
