{{- if .Values.webhook.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "k8s-sustain.webhookName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "k8s-sustain.labels" . | nindent 4 }}
    app.kubernetes.io/component: webhook
spec:
  type: ClusterIP
  selector:
    {{- include "k8s-sustain.webhookSelectorLabels" . | nindent 4 }}
  ports:
    - name: https
      port: 443
      targetPort: {{ .Values.webhook.port }}
      protocol: TCP
{{- end }}
