//go:build !ignore_autogenerated

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto copies all properties of this object into another object of the same type.
func (in *Policy) DeepCopyInto(out *Policy) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy creates a deep copy of Policy.
func (in *Policy) DeepCopy() *Policy {
	if in == nil {
		return nil
	}
	out := new(Policy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject implements runtime.Object.
func (in *Policy) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto copies all properties of this object into another object of the same type.
func (in *PolicyList) DeepCopyInto(out *PolicyList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Policy, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy creates a deep copy of PolicyList.
func (in *PolicyList) DeepCopy() *PolicyList {
	if in == nil {
		return nil
	}
	out := new(PolicyList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject implements runtime.Object.
func (in *PolicyList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto copies all properties of this object into another object of the same type.
func (in *PolicySelector) DeepCopyInto(out *PolicySelector) {
	*out = *in
	if in.Namespaces != nil {
		in, out := &in.Namespaces, &out.Namespaces
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.LabelSelector != nil {
		in, out := &in.LabelSelector, &out.LabelSelector
		*out = new(metav1.LabelSelector)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy creates a deep copy of PolicySelector.
func (in *PolicySelector) DeepCopy() *PolicySelector {
	if in == nil {
		return nil
	}
	out := new(PolicySelector)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto copies all properties of this object into another object of the same type.
func (in *PolicySpec) DeepCopyInto(out *PolicySpec) {
	*out = *in
	in.Selector.DeepCopyInto(&out.Selector)
	in.RightSizing.DeepCopyInto(&out.RightSizing)
	in.Update.DeepCopyInto(&out.Update)
}

// DeepCopy creates a deep copy of PolicySpec.
func (in *PolicySpec) DeepCopy() *PolicySpec {
	if in == nil {
		return nil
	}
	out := new(PolicySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto copies all properties of this object into another object of the same type.
func (in *PolicyStatus) DeepCopyInto(out *PolicyStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy creates a deep copy of PolicyStatus.
func (in *PolicyStatus) DeepCopy() *PolicyStatus {
	if in == nil {
		return nil
	}
	out := new(PolicyStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto copies all properties of this object into another object of the same type.
func (in *RightSizingSpec) DeepCopyInto(out *RightSizingSpec) {
	*out = *in
	out.UpdatePolicy = in.UpdatePolicy
	in.ResourcesConfigs.DeepCopyInto(&out.ResourcesConfigs)
}

// DeepCopy creates a deep copy of RightSizingSpec.
func (in *RightSizingSpec) DeepCopy() *RightSizingSpec {
	if in == nil {
		return nil
	}
	out := new(RightSizingSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto copies all properties of this object into another object of the same type.
func (in *RightSizingUpdatePolicy) DeepCopyInto(out *RightSizingUpdatePolicy) {
	*out = *in
}

// DeepCopy creates a deep copy of RightSizingUpdatePolicy.
func (in *RightSizingUpdatePolicy) DeepCopy() *RightSizingUpdatePolicy {
	if in == nil {
		return nil
	}
	out := new(RightSizingUpdatePolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto copies all properties of this object into another object of the same type.
func (in *ResourcesConfigs) DeepCopyInto(out *ResourcesConfigs) {
	*out = *in
	in.CPU.DeepCopyInto(&out.CPU)
	in.Memory.DeepCopyInto(&out.Memory)
}

// DeepCopy creates a deep copy of ResourcesConfigs.
func (in *ResourcesConfigs) DeepCopy() *ResourcesConfigs {
	if in == nil {
		return nil
	}
	out := new(ResourcesConfigs)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto copies all properties of this object into another object of the same type.
func (in *ResourceConfig) DeepCopyInto(out *ResourceConfig) {
	*out = *in
	in.Requests.DeepCopyInto(&out.Requests)
	in.Limits.DeepCopyInto(&out.Limits)
}

// DeepCopy creates a deep copy of ResourceConfig.
func (in *ResourceConfig) DeepCopy() *ResourceConfig {
	if in == nil {
		return nil
	}
	out := new(ResourceConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto copies all properties of this object into another object of the same type.
func (in *ResourceRequestsConfig) DeepCopyInto(out *ResourceRequestsConfig) {
	*out = *in
	if in.HeadroomPercentage != nil {
		x := *in.HeadroomPercentage
		out.HeadroomPercentage = &x
	}
	if in.MaxAllowed != nil {
		x := in.MaxAllowed.DeepCopy()
		out.MaxAllowed = &x
	}
	if in.MinAllowed != nil {
		x := in.MinAllowed.DeepCopy()
		out.MinAllowed = &x
	}
	if in.PercentilePercentage != nil {
		x := *in.PercentilePercentage
		out.PercentilePercentage = &x
	}
}

// DeepCopy creates a deep copy of ResourceRequestsConfig.
func (in *ResourceRequestsConfig) DeepCopy() *ResourceRequestsConfig {
	if in == nil {
		return nil
	}
	out := new(ResourceRequestsConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto copies all properties of this object into another object of the same type.
func (in *ResourceLimitsConfig) DeepCopyInto(out *ResourceLimitsConfig) {
	*out = *in
	if in.RequestsLimitsRatio != nil {
		x := *in.RequestsLimitsRatio
		out.RequestsLimitsRatio = &x
	}
}

// DeepCopy creates a deep copy of ResourceLimitsConfig.
func (in *ResourceLimitsConfig) DeepCopy() *ResourceLimitsConfig {
	if in == nil {
		return nil
	}
	out := new(ResourceLimitsConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto copies all properties of this object into another object of the same type.
func (in *UpdateSpec) DeepCopyInto(out *UpdateSpec) {
	*out = *in
	in.Types.DeepCopyInto(&out.Types)
}

// DeepCopy creates a deep copy of UpdateSpec.
func (in *UpdateSpec) DeepCopy() *UpdateSpec {
	if in == nil {
		return nil
	}
	out := new(UpdateSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto copies all properties of this object into another object of the same type.
func (in *UpdateTypes) DeepCopyInto(out *UpdateTypes) {
	*out = *in
	if in.Deployment != nil {
		x := *in.Deployment
		out.Deployment = &x
	}
	if in.StatefulSet != nil {
		x := *in.StatefulSet
		out.StatefulSet = &x
	}
	if in.DaemonSet != nil {
		x := *in.DaemonSet
		out.DaemonSet = &x
	}
	if in.CronJob != nil {
		x := *in.CronJob
		out.CronJob = &x
	}
	if in.Job != nil {
		x := *in.Job
		out.Job = &x
	}
	if in.Family != nil {
		x := *in.Family
		out.Family = &x
	}
	if in.DeploymentConfig != nil {
		x := *in.DeploymentConfig
		out.DeploymentConfig = &x
	}
	if in.ArgoRollout != nil {
		x := *in.ArgoRollout
		out.ArgoRollout = &x
	}
}

// DeepCopy creates a deep copy of UpdateTypes.
func (in *UpdateTypes) DeepCopy() *UpdateTypes {
	if in == nil {
		return nil
	}
	out := new(UpdateTypes)
	in.DeepCopyInto(out)
	return out
}
