name: Publish Docs

on:
  push:
    branches: [main]
    paths:
      - docs/**
      - mkdocs.yml
  workflow_dispatch:

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0   # needed for git-revision-date-localized plugin

      - uses: actions/setup-python@v5
        with:
          python-version: 3.x

      - name: Cache pip packages
        uses: actions/cache@v4
        with:
          key: mkdocs-material-${{ hashFiles('**/requirements-docs.txt') }}
          path: ~/.cache/pip

      - name: Install dependencies
        run: pip install -r requirements-docs.txt

      - name: Deploy to GitHub Pages
        run: mkdocs gh-deploy --force
